name: Daily Scraper 
on:
  schedule:
    - cron: '14 * * * *' # Runs at the start of every hour
  workflow_dispatch: # Keep this! It's great for manual testing.

jobs:
  build:
    runs-on: ubuntu-latest
    # Add these permissions so the bot can push the CSV back to the repo
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run scraper
        env:
          STUDIO_PASS: ${{ secrets.STUDIO_PASS }} # This maps the secret to os.getenv
        run: python scraper.py


      - name: Commit and push changes
        run: |
          git config --global user.name "Scraper Bot"
          git config --global user.email "bot@github.com"
          git pull origin main --rebase
          git add stats.csv user_breakdown.csv 
          git commit -m "Update stats" || exit 0
          git push

